attributes:
  horizon_crt:
    value: ""
    label: "CRT"
    description: "Certificate .crt content"
    weight: 10
    type: "password"
  horizon_key:
    value: ""
    label: "Key"
    description: "Certificate .key content"
    weight: 11
    type: "password"
  horizon_ca:
    value: ""
    label: "CA"
    description: "Certificate .ca content"
    weight: 12
    type: "password"